language: python
dist: xenial
python:
- "3.6"
- "3.7"
install: pip install tox-travis codecov
script: tox
after_success: codecov

jobs:
  include:
  - python: "3.5"
    env: TOXENV=docs
  - stage: deploy
    if: tag IS present
    python: "3.7"
    install: skip
    script: skip
    after_success: skip
    deploy:
      provider: pypi
      user: codingjoe
      distributions: sdist bdist_wheel
      on:
        tags: true
      password:
